/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiempoRouteImport } from './routes/tiempo'
import { Route as RiesgosRouteImport } from './routes/riesgos'
import { Route as ReunionesRouteImport } from './routes/reuniones'
import { Route as ReglasRouteImport } from './routes/reglas'
import { Route as RecordatoriosRouteImport } from './routes/recordatorios'
import { Route as PresupuestoRouteImport } from './routes/presupuesto'
import { Route as PlantillasRouteImport } from './routes/plantillas'
import { Route as HabitosRouteImport } from './routes/habitos'
import { Route as GanttRouteImport } from './routes/gantt'
import { Route as EvaluacionRouteImport } from './routes/evaluacion'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as EnfoqueRouteImport } from './routes/enfoque'
import { Route as CargaRouteImport } from './routes/carga'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AutoEstadosRouteImport } from './routes/auto-estados'
import { Route as ActividadesRouteImport } from './routes/actividades'
import { Route as IndexRouteImport } from './routes/index'

const TiempoRoute = TiempoRouteImport.update({
  id: '/tiempo',
  path: '/tiempo',
  getParentRoute: () => rootRouteImport,
} as any)
const RiesgosRoute = RiesgosRouteImport.update({
  id: '/riesgos',
  path: '/riesgos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReunionesRoute = ReunionesRouteImport.update({
  id: '/reuniones',
  path: '/reuniones',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglasRoute = ReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordatoriosRoute = RecordatoriosRouteImport.update({
  id: '/recordatorios',
  path: '/recordatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestoRoute = PresupuestoRouteImport.update({
  id: '/presupuesto',
  path: '/presupuesto',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantillasRoute = PlantillasRouteImport.update({
  id: '/plantillas',
  path: '/plantillas',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitosRoute = HabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => rootRouteImport,
} as any)
const GanttRoute = GanttRouteImport.update({
  id: '/gantt',
  path: '/gantt',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionRoute = EvaluacionRouteImport.update({
  id: '/evaluacion',
  path: '/evaluacion',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfoqueRoute = EnfoqueRouteImport.update({
  id: '/enfoque',
  path: '/enfoque',
  getParentRoute: () => rootRouteImport,
} as any)
const CargaRoute = CargaRouteImport.update({
  id: '/carga',
  path: '/carga',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoEstadosRoute = AutoEstadosRouteImport.update({
  id: '/auto-estados',
  path: '/auto-estados',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesRoute = ActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/auto-estados': typeof AutoEstadosRoute
  '/calendario': typeof CalendarioRoute
  '/carga': typeof CargaRoute
  '/enfoque': typeof EnfoqueRoute
  '/equipo': typeof EquipoRoute
  '/evaluacion': typeof EvaluacionRoute
  '/gantt': typeof GanttRoute
  '/habitos': typeof HabitosRoute
  '/plantillas': typeof PlantillasRoute
  '/presupuesto': typeof PresupuestoRoute
  '/recordatorios': typeof RecordatoriosRoute
  '/reglas': typeof ReglasRoute
  '/reuniones': typeof ReunionesRoute
  '/riesgos': typeof RiesgosRoute
  '/tiempo': typeof TiempoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/auto-estados': typeof AutoEstadosRoute
  '/calendario': typeof CalendarioRoute
  '/carga': typeof CargaRoute
  '/enfoque': typeof EnfoqueRoute
  '/equipo': typeof EquipoRoute
  '/evaluacion': typeof EvaluacionRoute
  '/gantt': typeof GanttRoute
  '/habitos': typeof HabitosRoute
  '/plantillas': typeof PlantillasRoute
  '/presupuesto': typeof PresupuestoRoute
  '/recordatorios': typeof RecordatoriosRoute
  '/reglas': typeof ReglasRoute
  '/reuniones': typeof ReunionesRoute
  '/riesgos': typeof RiesgosRoute
  '/tiempo': typeof TiempoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/auto-estados': typeof AutoEstadosRoute
  '/calendario': typeof CalendarioRoute
  '/carga': typeof CargaRoute
  '/enfoque': typeof EnfoqueRoute
  '/equipo': typeof EquipoRoute
  '/evaluacion': typeof EvaluacionRoute
  '/gantt': typeof GanttRoute
  '/habitos': typeof HabitosRoute
  '/plantillas': typeof PlantillasRoute
  '/presupuesto': typeof PresupuestoRoute
  '/recordatorios': typeof RecordatoriosRoute
  '/reglas': typeof ReglasRoute
  '/reuniones': typeof ReunionesRoute
  '/riesgos': typeof RiesgosRoute
  '/tiempo': typeof TiempoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actividades'
    | '/auto-estados'
    | '/calendario'
    | '/carga'
    | '/enfoque'
    | '/equipo'
    | '/evaluacion'
    | '/gantt'
    | '/habitos'
    | '/plantillas'
    | '/presupuesto'
    | '/recordatorios'
    | '/reglas'
    | '/reuniones'
    | '/riesgos'
    | '/tiempo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actividades'
    | '/auto-estados'
    | '/calendario'
    | '/carga'
    | '/enfoque'
    | '/equipo'
    | '/evaluacion'
    | '/gantt'
    | '/habitos'
    | '/plantillas'
    | '/presupuesto'
    | '/recordatorios'
    | '/reglas'
    | '/reuniones'
    | '/riesgos'
    | '/tiempo'
  id:
    | '__root__'
    | '/'
    | '/actividades'
    | '/auto-estados'
    | '/calendario'
    | '/carga'
    | '/enfoque'
    | '/equipo'
    | '/evaluacion'
    | '/gantt'
    | '/habitos'
    | '/plantillas'
    | '/presupuesto'
    | '/recordatorios'
    | '/reglas'
    | '/reuniones'
    | '/riesgos'
    | '/tiempo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActividadesRoute: typeof ActividadesRoute
  AutoEstadosRoute: typeof AutoEstadosRoute
  CalendarioRoute: typeof CalendarioRoute
  CargaRoute: typeof CargaRoute
  EnfoqueRoute: typeof EnfoqueRoute
  EquipoRoute: typeof EquipoRoute
  EvaluacionRoute: typeof EvaluacionRoute
  GanttRoute: typeof GanttRoute
  HabitosRoute: typeof HabitosRoute
  PlantillasRoute: typeof PlantillasRoute
  PresupuestoRoute: typeof PresupuestoRoute
  RecordatoriosRoute: typeof RecordatoriosRoute
  ReglasRoute: typeof ReglasRoute
  ReunionesRoute: typeof ReunionesRoute
  RiesgosRoute: typeof RiesgosRoute
  TiempoRoute: typeof TiempoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tiempo': {
      id: '/tiempo'
      path: '/tiempo'
      fullPath: '/tiempo'
      preLoaderRoute: typeof TiempoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riesgos': {
      id: '/riesgos'
      path: '/riesgos'
      fullPath: '/riesgos'
      preLoaderRoute: typeof RiesgosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reuniones': {
      id: '/reuniones'
      path: '/reuniones'
      fullPath: '/reuniones'
      preLoaderRoute: typeof ReunionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglas': {
      id: '/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof ReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordatorios': {
      id: '/recordatorios'
      path: '/recordatorios'
      fullPath: '/recordatorios'
      preLoaderRoute: typeof RecordatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuesto': {
      id: '/presupuesto'
      path: '/presupuesto'
      fullPath: '/presupuesto'
      preLoaderRoute: typeof PresupuestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantillas': {
      id: '/plantillas'
      path: '/plantillas'
      fullPath: '/plantillas'
      preLoaderRoute: typeof PlantillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitos': {
      id: '/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof HabitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gantt': {
      id: '/gantt'
      path: '/gantt'
      fullPath: '/gantt'
      preLoaderRoute: typeof GanttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluacion': {
      id: '/evaluacion'
      path: '/evaluacion'
      fullPath: '/evaluacion'
      preLoaderRoute: typeof EvaluacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfoque': {
      id: '/enfoque'
      path: '/enfoque'
      fullPath: '/enfoque'
      preLoaderRoute: typeof EnfoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carga': {
      id: '/carga'
      path: '/carga'
      fullPath: '/carga'
      preLoaderRoute: typeof CargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-estados': {
      id: '/auto-estados'
      path: '/auto-estados'
      fullPath: '/auto-estados'
      preLoaderRoute: typeof AutoEstadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividades': {
      id: '/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof ActividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActividadesRoute: ActividadesRoute,
  AutoEstadosRoute: AutoEstadosRoute,
  CalendarioRoute: CalendarioRoute,
  CargaRoute: CargaRoute,
  EnfoqueRoute: EnfoqueRoute,
  EquipoRoute: EquipoRoute,
  EvaluacionRoute: EvaluacionRoute,
  GanttRoute: GanttRoute,
  HabitosRoute: HabitosRoute,
  PlantillasRoute: PlantillasRoute,
  PresupuestoRoute: PresupuestoRoute,
  RecordatoriosRoute: RecordatoriosRoute,
  ReglasRoute: ReglasRoute,
  ReunionesRoute: ReunionesRoute,
  RiesgosRoute: RiesgosRoute,
  TiempoRoute: TiempoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
