/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTiempoRouteImport } from './routes/_authenticated/tiempo'
import { Route as AuthenticatedRiesgosRouteImport } from './routes/_authenticated/riesgos'
import { Route as AuthenticatedReunionesRouteImport } from './routes/_authenticated/reuniones'
import { Route as AuthenticatedReglasRouteImport } from './routes/_authenticated/reglas'
import { Route as AuthenticatedRecordatoriosRouteImport } from './routes/_authenticated/recordatorios'
import { Route as AuthenticatedPresupuestoRouteImport } from './routes/_authenticated/presupuesto'
import { Route as AuthenticatedPlantillasRouteImport } from './routes/_authenticated/plantillas'
import { Route as AuthenticatedHabitosRouteImport } from './routes/_authenticated/habitos'
import { Route as AuthenticatedGanttRouteImport } from './routes/_authenticated/gantt'
import { Route as AuthenticatedEvaluacionRouteImport } from './routes/_authenticated/evaluacion'
import { Route as AuthenticatedEquipoRouteImport } from './routes/_authenticated/equipo'
import { Route as AuthenticatedEnfoqueRouteImport } from './routes/_authenticated/enfoque'
import { Route as AuthenticatedCargaRouteImport } from './routes/_authenticated/carga'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAutoEstadosRouteImport } from './routes/_authenticated/auto-estados'
import { Route as AuthenticatedActividadesRouteImport } from './routes/_authenticated/actividades'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTiempoRoute = AuthenticatedTiempoRouteImport.update({
  id: '/_authenticated/tiempo',
  path: '/tiempo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRiesgosRoute = AuthenticatedRiesgosRouteImport.update({
  id: '/_authenticated/riesgos',
  path: '/riesgos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReunionesRoute = AuthenticatedReunionesRouteImport.update({
  id: '/_authenticated/reuniones',
  path: '/reuniones',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReglasRoute = AuthenticatedReglasRouteImport.update({
  id: '/_authenticated/reglas',
  path: '/reglas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecordatoriosRoute =
  AuthenticatedRecordatoriosRouteImport.update({
    id: '/_authenticated/recordatorios',
    path: '/recordatorios',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPresupuestoRoute =
  AuthenticatedPresupuestoRouteImport.update({
    id: '/_authenticated/presupuesto',
    path: '/presupuesto',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlantillasRoute = AuthenticatedPlantillasRouteImport.update({
  id: '/_authenticated/plantillas',
  path: '/plantillas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHabitosRoute = AuthenticatedHabitosRouteImport.update({
  id: '/_authenticated/habitos',
  path: '/habitos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGanttRoute = AuthenticatedGanttRouteImport.update({
  id: '/_authenticated/gantt',
  path: '/gantt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEvaluacionRoute = AuthenticatedEvaluacionRouteImport.update({
  id: '/_authenticated/evaluacion',
  path: '/evaluacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEquipoRoute = AuthenticatedEquipoRouteImport.update({
  id: '/_authenticated/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEnfoqueRoute = AuthenticatedEnfoqueRouteImport.update({
  id: '/_authenticated/enfoque',
  path: '/enfoque',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCargaRoute = AuthenticatedCargaRouteImport.update({
  id: '/_authenticated/carga',
  path: '/carga',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/_authenticated/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAutoEstadosRoute =
  AuthenticatedAutoEstadosRouteImport.update({
    id: '/_authenticated/auto-estados',
    path: '/auto-estados',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedActividadesRoute =
  AuthenticatedActividadesRouteImport.update({
    id: '/_authenticated/actividades',
    path: '/actividades',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/actividades': typeof AuthenticatedActividadesRoute
  '/auto-estados': typeof AuthenticatedAutoEstadosRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/carga': typeof AuthenticatedCargaRoute
  '/enfoque': typeof AuthenticatedEnfoqueRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/evaluacion': typeof AuthenticatedEvaluacionRoute
  '/gantt': typeof AuthenticatedGanttRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/plantillas': typeof AuthenticatedPlantillasRoute
  '/presupuesto': typeof AuthenticatedPresupuestoRoute
  '/recordatorios': typeof AuthenticatedRecordatoriosRoute
  '/reglas': typeof AuthenticatedReglasRoute
  '/reuniones': typeof AuthenticatedReunionesRoute
  '/riesgos': typeof AuthenticatedRiesgosRoute
  '/tiempo': typeof AuthenticatedTiempoRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/actividades': typeof AuthenticatedActividadesRoute
  '/auto-estados': typeof AuthenticatedAutoEstadosRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/carga': typeof AuthenticatedCargaRoute
  '/enfoque': typeof AuthenticatedEnfoqueRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/evaluacion': typeof AuthenticatedEvaluacionRoute
  '/gantt': typeof AuthenticatedGanttRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/plantillas': typeof AuthenticatedPlantillasRoute
  '/presupuesto': typeof AuthenticatedPresupuestoRoute
  '/recordatorios': typeof AuthenticatedRecordatoriosRoute
  '/reglas': typeof AuthenticatedReglasRoute
  '/reuniones': typeof AuthenticatedReunionesRoute
  '/riesgos': typeof AuthenticatedRiesgosRoute
  '/tiempo': typeof AuthenticatedTiempoRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/actividades': typeof AuthenticatedActividadesRoute
  '/_authenticated/auto-estados': typeof AuthenticatedAutoEstadosRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/carga': typeof AuthenticatedCargaRoute
  '/_authenticated/enfoque': typeof AuthenticatedEnfoqueRoute
  '/_authenticated/equipo': typeof AuthenticatedEquipoRoute
  '/_authenticated/evaluacion': typeof AuthenticatedEvaluacionRoute
  '/_authenticated/gantt': typeof AuthenticatedGanttRoute
  '/_authenticated/habitos': typeof AuthenticatedHabitosRoute
  '/_authenticated/plantillas': typeof AuthenticatedPlantillasRoute
  '/_authenticated/presupuesto': typeof AuthenticatedPresupuestoRoute
  '/_authenticated/recordatorios': typeof AuthenticatedRecordatoriosRoute
  '/_authenticated/reglas': typeof AuthenticatedReglasRoute
  '/_authenticated/reuniones': typeof AuthenticatedReunionesRoute
  '/_authenticated/riesgos': typeof AuthenticatedRiesgosRoute
  '/_authenticated/tiempo': typeof AuthenticatedTiempoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/actividades'
    | '/auto-estados'
    | '/calendario'
    | '/carga'
    | '/enfoque'
    | '/equipo'
    | '/evaluacion'
    | '/gantt'
    | '/habitos'
    | '/plantillas'
    | '/presupuesto'
    | '/recordatorios'
    | '/reglas'
    | '/reuniones'
    | '/riesgos'
    | '/tiempo'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/actividades'
    | '/auto-estados'
    | '/calendario'
    | '/carga'
    | '/enfoque'
    | '/equipo'
    | '/evaluacion'
    | '/gantt'
    | '/habitos'
    | '/plantillas'
    | '/presupuesto'
    | '/recordatorios'
    | '/reglas'
    | '/reuniones'
    | '/riesgos'
    | '/tiempo'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/actividades'
    | '/_authenticated/auto-estados'
    | '/_authenticated/calendario'
    | '/_authenticated/carga'
    | '/_authenticated/enfoque'
    | '/_authenticated/equipo'
    | '/_authenticated/evaluacion'
    | '/_authenticated/gantt'
    | '/_authenticated/habitos'
    | '/_authenticated/plantillas'
    | '/_authenticated/presupuesto'
    | '/_authenticated/recordatorios'
    | '/_authenticated/reglas'
    | '/_authenticated/reuniones'
    | '/_authenticated/riesgos'
    | '/_authenticated/tiempo'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedActividadesRoute: typeof AuthenticatedActividadesRoute
  AuthenticatedAutoEstadosRoute: typeof AuthenticatedAutoEstadosRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCargaRoute: typeof AuthenticatedCargaRoute
  AuthenticatedEnfoqueRoute: typeof AuthenticatedEnfoqueRoute
  AuthenticatedEquipoRoute: typeof AuthenticatedEquipoRoute
  AuthenticatedEvaluacionRoute: typeof AuthenticatedEvaluacionRoute
  AuthenticatedGanttRoute: typeof AuthenticatedGanttRoute
  AuthenticatedHabitosRoute: typeof AuthenticatedHabitosRoute
  AuthenticatedPlantillasRoute: typeof AuthenticatedPlantillasRoute
  AuthenticatedPresupuestoRoute: typeof AuthenticatedPresupuestoRoute
  AuthenticatedRecordatoriosRoute: typeof AuthenticatedRecordatoriosRoute
  AuthenticatedReglasRoute: typeof AuthenticatedReglasRoute
  AuthenticatedReunionesRoute: typeof AuthenticatedReunionesRoute
  AuthenticatedRiesgosRoute: typeof AuthenticatedRiesgosRoute
  AuthenticatedTiempoRoute: typeof AuthenticatedTiempoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tiempo': {
      id: '/_authenticated/tiempo'
      path: '/tiempo'
      fullPath: '/tiempo'
      preLoaderRoute: typeof AuthenticatedTiempoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/riesgos': {
      id: '/_authenticated/riesgos'
      path: '/riesgos'
      fullPath: '/riesgos'
      preLoaderRoute: typeof AuthenticatedRiesgosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reuniones': {
      id: '/_authenticated/reuniones'
      path: '/reuniones'
      fullPath: '/reuniones'
      preLoaderRoute: typeof AuthenticatedReunionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reglas': {
      id: '/_authenticated/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof AuthenticatedReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recordatorios': {
      id: '/_authenticated/recordatorios'
      path: '/recordatorios'
      fullPath: '/recordatorios'
      preLoaderRoute: typeof AuthenticatedRecordatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/presupuesto': {
      id: '/_authenticated/presupuesto'
      path: '/presupuesto'
      fullPath: '/presupuesto'
      preLoaderRoute: typeof AuthenticatedPresupuestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plantillas': {
      id: '/_authenticated/plantillas'
      path: '/plantillas'
      fullPath: '/plantillas'
      preLoaderRoute: typeof AuthenticatedPlantillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/habitos': {
      id: '/_authenticated/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof AuthenticatedHabitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gantt': {
      id: '/_authenticated/gantt'
      path: '/gantt'
      fullPath: '/gantt'
      preLoaderRoute: typeof AuthenticatedGanttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/evaluacion': {
      id: '/_authenticated/evaluacion'
      path: '/evaluacion'
      fullPath: '/evaluacion'
      preLoaderRoute: typeof AuthenticatedEvaluacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/equipo': {
      id: '/_authenticated/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AuthenticatedEquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/enfoque': {
      id: '/_authenticated/enfoque'
      path: '/enfoque'
      fullPath: '/enfoque'
      preLoaderRoute: typeof AuthenticatedEnfoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/carga': {
      id: '/_authenticated/carga'
      path: '/carga'
      fullPath: '/carga'
      preLoaderRoute: typeof AuthenticatedCargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auto-estados': {
      id: '/_authenticated/auto-estados'
      path: '/auto-estados'
      fullPath: '/auto-estados'
      preLoaderRoute: typeof AuthenticatedAutoEstadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/actividades': {
      id: '/_authenticated/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof AuthenticatedActividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedActividadesRoute: AuthenticatedActividadesRoute,
  AuthenticatedAutoEstadosRoute: AuthenticatedAutoEstadosRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCargaRoute: AuthenticatedCargaRoute,
  AuthenticatedEnfoqueRoute: AuthenticatedEnfoqueRoute,
  AuthenticatedEquipoRoute: AuthenticatedEquipoRoute,
  AuthenticatedEvaluacionRoute: AuthenticatedEvaluacionRoute,
  AuthenticatedGanttRoute: AuthenticatedGanttRoute,
  AuthenticatedHabitosRoute: AuthenticatedHabitosRoute,
  AuthenticatedPlantillasRoute: AuthenticatedPlantillasRoute,
  AuthenticatedPresupuestoRoute: AuthenticatedPresupuestoRoute,
  AuthenticatedRecordatoriosRoute: AuthenticatedRecordatoriosRoute,
  AuthenticatedReglasRoute: AuthenticatedReglasRoute,
  AuthenticatedReunionesRoute: AuthenticatedReunionesRoute,
  AuthenticatedRiesgosRoute: AuthenticatedRiesgosRoute,
  AuthenticatedTiempoRoute: AuthenticatedTiempoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
